# ─────────────────────────────────────────────────────────────────────────────
#  PDF RAG — serve image  (FastAPI + LanceDB, NO extraction pipeline)
#
#  Multi-stage build:
#    deps       — install Python packages (cached unless requirements change)
#    model      — download BAAI/bge-small-en-v1.5 (~90 MB, cached separately)
#    runtime    — lean final image with app code + pre-built index baked in
#
#  Pre-requisites (run locally before docker build):
#    python scripts/index_and_serve.py index --pdf <path> --out output
#
#  Build:
#    docker build -t pdf-rag-api .
#
#  Run locally:
#    docker run --rm -p 8000:8000 --env-file .env pdf-rag-api
#    open http://localhost:8000/docs
# ─────────────────────────────────────────────────────────────────────────────

# ── Stage 1: Python dependency installation ───────────────────────────────────
FROM python:3.12-slim AS deps

# System libs:
#   libgomp1 — OpenMP, required by lancedb / faiss C extensions
#   curl     — used in HEALTHCHECK
RUN apt-get update \
    && apt-get install -y --no-install-recommends libgomp1 curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-serve.txt /tmp/
RUN pip install --no-cache-dir \
        --extra-index-url https://download.pytorch.org/whl/cpu \
        -r /tmp/requirements-serve.txt


# ── Stage 2: pre-download the embedding model ─────────────────────────────────
# Baked into its own layer so it only re-runs when the model name changes,
# not when the application code changes.
FROM deps AS model

ENV SENTENCE_TRANSFORMERS_HOME=/opt/st_cache \
    HF_HOME=/opt/hf_cache

RUN python -c "\
from sentence_transformers import SentenceTransformer; \
SentenceTransformer('BAAI/bge-small-en-v1.5'); \
print('Model cached OK')"


# ── Stage 3: runtime image ────────────────────────────────────────────────────
FROM deps AS runtime

# Copy the pre-downloaded model cache from stage 2
ENV SENTENCE_TRANSFORMERS_HOME=/opt/st_cache \
    HF_HOME=/opt/hf_cache

COPY --from=model /opt/st_cache /opt/st_cache
COPY --from=model /opt/hf_cache /opt/hf_cache

WORKDIR /app

# Install the package (src layout — hatchling reads [tool.hatch.build] sources)
COPY pyproject.toml ./
COPY src/ ./src/
COPY main.py ./
RUN pip install --no-cache-dir -e . --no-deps 2>/dev/null || true

# PYTHONPATH fallback in case editable install isn't on sys.path
ENV PYTHONPATH=/app/src

# Pre-built LanceDB index and extracted page data.
# Generated by: python scripts/index_and_serve.py index --pdf <path> --out output
#
# To use a Docker volume instead of baking in:
#   - Remove these two COPY lines
#   - Add volume mounts in docker-compose.yml or at `docker run` time
#   - Example: docker run -v ./lancedb_index:/app/lancedb_index \
#                         -v ./output:/app/output ...
COPY lancedb_index/ ./lancedb_index/
COPY output/        ./output/

EXPOSE 8000

# Readiness probe — Cloud Run, Railway, and Fly.io all use this.
# start-period gives the warm-up (encoder load) 90 s to complete.
HEALTHCHECK --interval=30s --timeout=10s --start-period=90s --retries=3 \
    CMD curl -f http://localhost:8000/health || exit 1

# PORT env var is injected by Railway / Fly.io / Cloud Run.
# Falls back to 8000 for local Docker runs.
ENV PORT=8000

CMD ["sh", "-c", \
     "manual-rag api \
      --index-dir lancedb_index \
      --out output \
      --port ${PORT}"]
